### ISSUE TITLE
Unable to upgrade sonarqube to community 7.9.6 edition due to sonarswift plugin

### ISSUE THREAD

**Issue by DeirdreRodgers** [Backelite/sonar-swift#293]
### Question Description
Hello,
I wonder if anyone has had a similar issue to me
I'm currently upgrading my sonarqube app which is hosted in K8s. I am on version 7.8-developer and intend to go to an 8.x developer version. Firstly though I need to upgrade to a community version 7.9.6 as this is an LTS version and there are no official developer images available for that version. It fails however when it tries to load the sonarswift plugin because its a community version. my version of the sonarswift plugin is 4.1 (build 3087)

Since I intend immediately upgrading to a later developer version after the upgrade to 7.9.6 community , would it be feasible to disable or uninstall the plugin before I upgrade and then reinstall when I am back on a developer version? or could this cause issues with my data ?

Or is there some other way around this?

```
2021.05.31 12:59:25 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
java.lang.IllegalStateException: Fail to load plugin SonarSwift [swift]
        at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:82)
        at org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:543)
        at org.sonar.server.platform.Platform.start(Platform.java:211)
        at org.sonar.server.platform.Platform.startLevel34Containers(Platform.java:185)
        at org.sonar.server.platform.Platform.access$500(Platform.java:46)
        at org.sonar.server.platform.Platform$1.lambda$doRun$0(Platform.java:119)
        at org.sonar.server.platform.Platform$AutoStarterRunnable.runIfNotAborted(Platform.java:371)
        at org.sonar.server.platform.Platform$1.doRun(Platform.java:119)
        at org.sonar.server.platform.Platform$AutoStarterRunnable.run(Platform.java:355)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: com/sonarsource/plugins/license/api/LicensedPluginRegistration
        at com.sonar.swift.plugin.SwiftPlugin.define(Unknown Source)
```

**Comment by rounak-codiant** [comment]
Did you find any workaround for this? 
We are also facing the issue, we have updated the sonarqube community edition from 7.9 to 8.9 and this plugin is not supporting with the updated version.

**Comment by zippy1978** [comment]
HI all,
Just in case we've been working on a new plugin (with more features) here: https://github.com/insideapp-oss/sonar-apple
