### ISSUE TITLE
sonarqube 9 library update

### ISSUE THREAD

**Issue by dariancampospeya** [Backelite/sonar-swift#296]
### Feature Request
How are you?
 Do you have any news about the update of the lib to be supported by sonarqube 9

**Comment by estebanhiguitad** [comment]
About this, when I update my sonarqube to 9.1 version I get this error:

```
2021.09.24 11:55:26 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
java.lang.NoSuchMethodError: 'org.sonar.api.server.rule.RulesDefinition$NewRule org.sonar.api.server.rule.RulesDefinition$NewRule.setDebtSubCharacteristic(java.lang.String)'
        at org.sonar.squidbridge.rules.SqaleXmlLoader.processRule(SqaleXmlLoader.java:124)
        at org.sonar.squidbridge.rules.SqaleXmlLoader.processSubChar(SqaleXmlLoader.java:92)
        at org.sonar.squidbridge.rules.SqaleXmlLoader.processRoot(SqaleXmlLoader.java:78)
        at org.sonar.squidbridge.rules.SqaleXmlLoader.loadXmlResource(SqaleXmlLoader.java:65)
        at org.sonar.squidbridge.rules.SqaleXmlLoader.load(SqaleXmlLoader.java:52)
        at com.backelite.sonarqube.swift.issues.swiftlint.SwiftLintRulesDefinition.define(SwiftLintRulesDefinition.java:61)
        at org.sonar.server.rule.RuleDefinitionsLoader.load(RuleDefinitionsLoader.java:53)
        at org.sonar.server.rule.RegisterRules.start(RegisterRules.java:119)
        at org.sonar.core.platform.StartableCloseableSafeLifecyleStrategy.start(StartableCloseableSafeLifecyleStrategy.java:40)
        at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84)
        at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169)
        at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132)
        at org.picocontainer.behaviors.Stored.start(Stored.java:110)
        at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016)
        at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009)
        at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
        at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:90)
        at org.sonar.server.platform.platformlevel.PlatformLevelStartup.access$001(PlatformLevelStartup.java:51)
        at org.sonar.server.platform.platformlevel.PlatformLevelStartup$1.doPrivileged(PlatformLevelStartup.java:119)
        at org.sonar.server.user.DoPrivileged.execute(DoPrivileged.java:45)
        at org.sonar.server.platform.platformlevel.PlatformLevelStartup.start(PlatformLevelStartup.java:116)
        at org.sonar.server.platform.PlatformImpl.executeStartupTasks(PlatformImpl.java:198)
        at org.sonar.server.platform.PlatformImpl$1.lambda$doRun$1(PlatformImpl.java:122)
        at org.sonar.server.platform.PlatformImpl$AutoStarterRunnable.runIfNotAborted(PlatformImpl.java:370)
        at org.sonar.server.platform.PlatformImpl$1.doRun(PlatformImpl.java:122)
        at org.sonar.server.platform.PlatformImpl$AutoStarterRunnable.run(PlatformImpl.java:354)
        at java.base/java.lang.Thread.run(Thread.java:829)
2021.09.24 11:55:27 INFO  web[][o.s.p.ProcessEntryPoint] Hard stopping process
2021.09.24 11:55:27 INFO  web[][o.s.s.n.NotificationDaemon] Notification service stopped
```

**Comment by estebanhiguitad** [comment]
Hi everyone

I have created a branch to resolve this issue. If any want to contribute to it can contact me by links un my Github profile to go ahead together. 

The branch:
[https://github.com/estebanhiguitad/sonar-swift/tree/update-rules-for-sonar-9](https://github.com/estebanhiguitad/sonar-swift/tree/update-rules-for-sonar-9)

**Comment by estebanhiguitad** [comment]
Hello.
It is becouse the plugin is not supported for Sonarqube 9. I am working on fix it in a branch. You want can use the artifact that I generate as SNAPSHOT mode and give me a feedback about it.

https://github.com/estebanhiguitad/sonar-swift/releases

Thanks

**Comment by ihard** [comment]
@estebanhiguitad it work, thanks!

**Comment by zippy1978** [comment]
HI all,
Just in case we've been working on a new plugin (with more features) here: https://github.com/insideapp-oss/sonar-apple

**Comment by magiciannimble** [comment]
@estebanhiguitad it's working, thank you Sir!

**Comment by magiciannimble** [comment]
> HI all, Just in case we've been working on a new plugin (with more features) here: https://github.com/insideapp-oss/sonar-apple

**sonar-apple** plugin is working very slow, documentation how to set sonar properties is pure, also absent some example how to use this plugin.  Inside antlr parser it's working slow, detecting duplicates working very slow. As result I return back to **sonar-swift** plugin with fix from @estebanhiguitad. 

https://github.com/insideapp-oss/sonar-apple/issues/95
